### ISSUE TITLE
图片向右旋转

### ISSUE THREAD

**Issue by zhouxiao87315** [rekoj/videoPlay#1]
我看当图片的长大于宽的时候，图片被向右旋转90度

**Comment by rekoj** [comment]
图片旋转？  是说视频中?

**Comment by zhouxiao87315** [comment]
- (CGImageRef) imageFromSampleBuffer:(CMSampleBufferRef) sampleBuffer rotation:(UIImageOrientation)orientation{
  CVImageBufferRef imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
  // Lock the base address of the pixel buffer
  CVPixelBufferLockBaseAddress(imageBuffer, 0);
  // Get the number of bytes per row for the pixel buffer
  size_t bytesPerRow = CVPixelBufferGetBytesPerRow(imageBuffer);
  // Get the pixel buffer width and height
  size_t width = CVPixelBufferGetWidth(imageBuffer);
  size_t height = CVPixelBufferGetHeight(imageBuffer);
  //Generate image to edit
  unsigned char\* pixel = (unsigned char *)CVPixelBufferGetBaseAddress(imageBuffer);
  CGColorSpaceRef colorSpace=CGColorSpaceCreateDeviceRGB();
  CGContextRef context=CGBitmapContextCreate(pixel, width, height, 8, bytesPerRow, colorSpace, kCGBitmapByteOrder32Little|kCGImageAlphaPremultipliedFirst);
  CGImageRef image = CGBitmapContextCreateImage(context);
  CGContextRelease(context);
  CGColorSpaceRelease(colorSpace);
  CVPixelBufferUnlockBaseAddress(imageBuffer, 0);
  UIGraphicsEndImageContext();
  
  return image;
  } ----- 是这段 CMSampleBufferRef 转 CGImageRef 的时候 orientation 的方向是UIImageOrientationRight。怎么样旋转成UIImageOrientationUp 呢？

**Comment by zhouxiao87315** [comment]
可以加qq交流一下吗？893316706
